### ISSUE TITLE
Do not delete name of route with children

### ISSUE THREAD

**Issue by bartlomieju** [nuxt-community/nuxt-i18n#116]
Hi!

Today I stumbled across a problem that deletes name of routes that have children. I think this is unexpected behaviour, as I tend to have directory structure like this:
<img width="224" alt="zrzut ekranu 2018-08-16 o 18 00 38" src="https://user-images.githubusercontent.com/13602871/44220245-53e0e900-a17e-11e8-942e-a31b18358f14.png">
and do a redirect in `vendors/_slug.vue` file. 

The culprit is this line:
https://github.com/nuxt-community/nuxt-i18n/blob/45ff90d1b8076c12f5c1a75fb7e2d398450e7c51/src/helpers/routes.js#L70

What is your opinion on this one?

**Comment by paulgv** [comment]
Hi @bartlomieju 
This change was made to fix a particular issue: https://github.com/nuxt-community/nuxt-i18n/issues/98
I don't remember the details exactly...
Does this prevent you from doing the redirection?

**Comment by bartlomieju** [comment]
Hi @paulgv sorry for trouble, it looks like my Nuxt route config is improper, I should have added `index.vue` file to `vendors` directory.

**Comment by paulgv** [comment]
@bartlomieju no worries! I was wondering why you didn't have that `index.vue` actually. All good then!

**Comment by berenicestr** [comment]
Hi @paulgv and @bartlomieju  I have the same error, I open a question: https://github.com/nuxt-community/nuxt-i18n/issues/286

I have the index.vue but it doesn't work for me.

Please, any help to resolve this?

**Comment by madmod** [comment]
@paulgv @bartlomieju I think this is breaking a valid use case because the assumption that routes with children should not have a name is incorrect. Navigating to a route which has children is valid and so those routes should be allowed a name.

I have a structure like this which works fine when I remove the deletion. 
![Screen Shot 2019-09-10 at 2.25.39 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/110467581/32a0e470-d409-11e9-8a53-a1ada666fa7c.png)
It is a page with tabs which has children. I need to redirect to the default tab by name for various reasons. This is supported by vue-router and works with nuxt when I disable the vue-i18n plugin.

**Comment by rchl** [comment]
@madmod there is actually already issue about that #356
