### ISSUE TITLE
I18n breaks possibility to load async components inside pages

### ISSUE THREAD

**Issue by webmint** [nuxt-community/nuxt-i18n#134]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://github.com/webmint/nuxt-i18n-bug](https://github.com/webmint/nuxt-i18n-bug)

### Steps to reproduce

1) Install nuxt install i18n.
2) in for example pages/index try to import components like this Logo: () => import('~/components/Logo'),
3) on build u will receive error. This error dissapear when removing async import from file or removing i18n

Also - this happens ONLY when u do such import in pages/**

![Screenshot from 2018-10-08 18-08-10.png](https://cmty.s3.eu-west-1.amazonaws.com/110467581/08177040-cb0c-11e8-a735-f5f2c9bc1d7a.png)

### What is expected ?

Load async component

### What is actually happening?

App fails

### Additional comments?

This problem was in 5.3.0 and also exists at 5.40

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c146">#c146</a>)</em></sub></div>

**Comment by rhwilr** [comment]
I'm running into the same issue. @webmint did you find a solution?

**Comment by rhwilr** [comment]
Never mind, I just found a solution: You have to set `parsePages: false` in the options for nuxt-i18n.
https://nuxt-community.github.io/nuxt-i18n/options-reference.html

**Comment by SirAuron** [comment]
Hi all.
Incurred into the same issue too.
The solution provided here actually works, but i find it a little bit annoying to move routes into a single file instead of the vue components used for the pages.
Currently, for me is no big deal, since I have to generate dynamic routes for a blog with a script reading some markdown files.
But I think this issue should be addressed.
I do not know I will have time in the near future, but if someone can point out how this issue is generated, I'm willing to give it a try and fix it.

**Comment by aldarund** [comment]
Isnt it this problem -> https://github.com/webpack/webpack/issues/8656 ?
