### ISSUE TITLE
nuxt-i18n <-> vuelidate dynamic validation issue

### ISSUE THREAD

**Issue by Magnum5234** [nuxt-community/nuxt-i18n#142]
### Version

[5.4.3](https://github.com/nuxt-i18n/releases/tag/5.4.3)

### Reproduction link

[https://codesandbox.io/s/vy54y194yy](https://codesandbox.io/s/vy54y194yy)

### Steps to reproduce

Apparently there seems to be an issue that the dynamic validations are no longer triggered, when "nuxt-i18n" is used.

I reproduced the issue here: 
[broken]
https://codesandbox.io/s/vy54y194yy

[working]
https://codesandbox.io/s/ywxknqooxv

The example is the one used in the vuelidate documentation: https://monterail.github.io/vuelidate/#sub-dynamic-validation-schema

The only difference between the working and broken example is that in the working one the module for nuxt-i18n is commented out in the nuxt config.

### What is expected ?

The expected behavior is that the validation configuration should change when the checkbox is clicked. 

### What is actually happening?

Validation configuration does not change.

### Additional comments?

Since I'm not really sure who can fix this issue I created this issue for nuxt-i18n and vuelidate.

Thanks in advance :)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c155">#c155</a>)</em></sub></div>

**Comment by Magnum5234** [comment]
Reference: https://github.com/monterail/vuelidate/issues/380

**Comment by Magnum5234** [comment]
There seems to be another compatibility issue. Please see https://github.com/monterail/vuelidate/issues/382 for reference

**Comment by luke-hawk** [comment]
+1

**Comment by dinaabramova** [comment]
+1

**Comment by farhadniaz** [comment]
I have same issue.
Is there any solution?

**Comment by sumitrathore1313** [comment]
I have finally solved it. I have been trying to solve it for the past 1 week.
### solution

add $v deep watch variable where you define validator object.
example -
watch: {
$v : {
handler: function(val) {
console.log("changed")
},
deep: true
}
},
validations: {
form: validationsform,
}

**Comment by dinaabramova** [comment]
@sumitrathore1313 
Add `console.log` is a great solution 👍 (hello, javascript magic)

My colleague accidentally did something similar, but it solved only one problem. There were another several problems that I described in [related issue](https://github.com/vuelidate/vuelidate/issues/380#issuecomment-443600837). It seems, that your solution should solve all of the problems.
I didn't check it, because I replaced vuelidate by vee-validate in all my projects. And it's great, vee-validate much more powerful than vuelidate, no conflicts, great support of vue-i18n (that Nuxt also uses) and migration was absolutely painless.
