### ISSUE TITLE
Change seo option to false for next major version

### ISSUE THREAD

**Issue by rchl** [nuxt-community/nuxt-i18n#346]
### What problem does this feature solve?

`seo = true` option is computationally expensive (https://nuxt-community.github.io/nuxt-i18n/seo.html#improving-performance), sometimes even breaks the code, and users typically don't need the functionality it provides and would be fine with using it the way the mentioned link describes.

### What does the proposed changes look like?

I suggest change `seo` option to `false` by default, update documentation regarding that and suggest using solution from https://nuxt-community.github.io/nuxt-i18n/seo.html#improving-performance
Those who really need that functionality will be able to change the option to `true`.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c256">#c256</a>)</em></sub></div>

**Comment by paulgv** [comment]
Thanks @rchl, I think this makes sense. Would you have some time to open a PR by any chance?

**Comment by hga77** [comment]
Guys, THIS MUST BE ADDED IN THE NEXT VERSION!!!! I just waisted a WHOLE DAY trying to figure out why my already built website had a a major issue with my page styles breaking on page route changes because my body class style kept changing all of a sudden. I spent the whole day looking into thing and resorted to changing my CSS to get it to work. The realised what if it's something to do with nuxt-i18n because I installed it the previous day! Then I see this, made seo:false, AND MY WEBSITE IS BACK TO NORMAL AGAIN!!!! (Yes i am extremly happy now!) Guys this is a bad design decision... Never force a setting on a user! Please disable in the next release!

**Comment by paulgv** [comment]
@hga77 That's the plan :) https://github.com/nuxt-community/nuxt-i18n/pull/362/commits/5115b5b45490ad198d0607a3ee5ee2eeeaf1cebd
