### ISSUE TITLE
defaultLocale with different domains (SSR)

### ISSUE THREAD

**Issue by aleks63** [nuxt-community/nuxt-i18n#387]
Hello.

I use different domains and I wanna load defaultLocale on each domain.
So that the contents of the page were already in the desired language during server loading. Now the content is in the language selected in the default Locale, regardless of the domain. How to do it?

**Comment by aleks63** [comment]
@galvez @hmsk @elrolito @rchl

**Comment by aleks63** [comment]
@paulgv

**Comment by moka491** [comment]
Would love to know that as well. However I guess since defaultLocale changes how the generated routes will look like (i.e. prefix or not), you'd have to somehow build two different "builds" of nuxt-i18n for each respective domain.

**Comment by moka491** [comment]
After weeks of trying around, I got a solution to this I think.
First of all, you can set a default locale for a different domain in nuxtServerInit in your vuex index.js file:

*store/index.js*
```js
export const actions = {
  nuxtServerInit(context, { req, redirect }) {
    if (req.headers.host.endsWith('com')) {
      this.app.i18n.defaultLocale = 'en'
    }
  },
```

This sets the defaultLocale, however it won't remove the prefixes of the paths for the new default locale, since the routes are already generated.
I had the same issue, and went three steps further to solve this:
I went and wrote a script, that takes the generated router.js file, adds a second routes array that holds the prefix-less paths for the new defaultLocale, and then depending on the request, serves either array to the router.

*build/generateRoutesForComSite.js*
```js
/* eslint-disable no-console */
const fs = require('fs')

const routerPath = '.nuxt/router.js'

const reRoutesArray = /(?<=routes:)\s+(\[[^\]]+\}\])(?=,)/gim

const reRemoveGermanRoutes = /{[^{}]+___de[^{}]+},?\s?/gis
const reMatchEnglishRoutes = /path:\s+"\/en\/([^"]+)"/gim

const reReplaceCreateRouter = /(export function createRouter.*\}\)\s+\})/gis

const createRouterFunction = `
export function createRouter(ssrContext) {
  const isCom = 
    ssrContext && ssrContext.req.headers.host.endsWith('com') || process.client && window.location.hostname.endsWith('com')

  let router = new Router({
    mode: 'history',
    base: decodeURI('/'),
    linkActiveClass: 'nuxt-link-active',
    linkExactActiveClass: 'nuxt-link-exact-active',
    scrollBehavior,

    routes: getRoutes(isCom),

    fallback: false
  })
  return router
}`

let getRoutesFunction = `
const getRoutes = (isCom) => {
  if(isCom) {
    return __COMROUTES__
  }
  return __ROUTES__
}`

export default function() {
  fs.readFile(routerPath, 'utf8', function(err, data) {
    if (err) {
      return console.log(err)
    }

    /* Extract routes array from router.js */
    const routesMatch = data.match(reRoutesArray)
    if (routesMatch && routesMatch.length > 0) {
      const routesArray = routesMatch[0]
      let comRoutesArray = routesArray

      /* Remove German routes */
      comRoutesArray = comRoutesArray.replace(reRemoveGermanRoutes, '')
      /* Remove /en/ on English routes */
      comRoutesArray = comRoutesArray.replace(
        reMatchEnglishRoutes,
        'path: "/$1"'
      )

      /* Insert modified createRouter function */
      data = data.replace(reReplaceCreateRouter, createRouterFunction)

      /* Insert routes into getRoutes function */
      getRoutesFunction = getRoutesFunction.replace('__ROUTES__', routesArray)
      getRoutesFunction = getRoutesFunction.replace(
        '__COMROUTES__',
        comRoutesArray
      )

      /* Insert getRoutes function */
      data += '\n' + getRoutesFunction
    }

    fs.writeFile(routerPath, data, 'utf8', function(err) {
      if (err) return console.log(err)
    })
  })
}

```

The script can then be added to the build process in 

*nuxt.config.js*
```
  /*
   ** Hooks that get called when building the project
   */
  hooks: {
    build: {
      compile() {
        generateRoutesForComSite()
      }
    }
  }
```

It stands to test how production ready the script is, that mainly depends on the specifity of the regular expressions.

**Comment by rchl** [comment]
> I use different domains and I wanna load defaultLocale on each domain.
> So that the contents of the page were already in the desired language during server loading. Now the content is in the language selected in the default Locale, regardless of the domain.

That is a bit confusing. You want to "load defaultLocale" on each domain? So same locale, since you define `defaultLocale` only once per app?
The rest of your message seems to imply that you want domain-specific locale to be chosen - so `fr` for `fr.domain.com` and `en` for `en.domain.com`. If that's the case, then this is how it should work currently (maybe you would need to set `detectBrowserLanguage: false` though, as that can cause confusion if something is stored in a cookie.

**Comment by mathroc** [comment]
@rchl I cannot speak for OP but in our case, we'd like to have a different default locale on different domains, but still be able to change locale on each domain, eg:

* https://www.site.com/ ⇒ fr
* https://www.site.com/en ⇒ en-US
* https://www.site.ch/ ⇒ fr-CH
* https://www.site.ch/de ⇒ de-CH
* https://www.site.ch/it ⇒ it-CH
* https://www.site.ch/en ⇒ en-US

**Comment by rchl** [comment]
@mathroc That case seems quite complicated. If feel like that would be a bit too much to support that for this module. And I don't see how it could be done either since routes are generated once per provided configuration and this use case seems like would require at least two different set of routes.

Maybe solution for you would be to actually have two separately built and deployed apps...

**Comment by tomiiide** [comment]
@mathroc How did you solve this problem eventually?

**Comment by mathroc** [comment]
> @mathroc How did you solve this problem eventually?

by building 2 slightly different build as suggested by @rchl . this was the fastest solution to get this working.

on a new version of the site we’re working on we're back to only one build but we’re not using this module anymore instead we have our own i18n plugin and middleware on top of the vue i18n plugin

**Comment by reflexator** [comment]
@mathroc Is possible to contribute your implementation? Thank you very much

**Comment by algj** [comment]
We really need a better solution.
