### ISSUE TITLE
Wrap consola dev statements in dev mode check

### ISSUE THREAD

**Issue by manniL** [nuxt-community/nuxt-i18n#421]
https://github.com/nuxt-community/nuxt-i18n/blob/617e31e8235ffdeb7d345c3b960701b616d94b72/src/plugins/routing.js#L17-L19

Checks like these should be wrapped in a lodash template and only be rendered in dev mode so that they aren't shipped in the production bundle IMO. WDYT? :relaxed:

**Comment by rchl** [comment]
I don't have strong opinions either way. In theory one should catch those warnings  when developing and fix them so that they don't reach production in the first place. But if they reach production, with warning enabled, there is extra chance of noticing the problem. Especially if something doesn't work as expected. Although I admit that that particular warning is quite internal in nature.

But I wonder... Doesn't nuxt automatically filter out console calls when building in production?

**Comment by manniL** [comment]
> But I wonder... Doesn't Nuxt automatically filter out console calls when building in production?

That's actually a good question. I guess that's not the case but @pi0 can enlighten us regarding that :relaxed:

**Comment by rchl** [comment]
I've tested it, it's not filtered out.

BTW. This log message is not using `consola`, but plain `console`.
