### ISSUE TITLE
After generating wrong page is loaded

### ISSUE THREAD

**Issue by pimlie** [nuxt-community/nuxt-i18n#451]
### Version

[v6.2.0](https://github.com/nuxt-i18n/releases/tag/v6.2.0)

### Reproduction link

[https://github.com/nuxt-community/lunr-module/tree/master/example](https://github.com/nuxt-community/lunr-module/tree/master/example)

### Steps to reproduce

Clone the lunr-module, upgrade nuxt-i18n to ^6.2.0 and run the test.

### What is expected ?

Test succeeds

### What is actually happening?

Test fails as the page `/af/` returns title for `/en/` 

### Additional comments?

Running `yarn dev` works fine, the issue is with generating. Probably related to #378

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c300">#c300</a>)</em></sub></div>

**Comment by rchl** [comment]
It seems expected since on first opening of the URL nuxt-i18n detects browser language and redirects to matching locale. So if the first URL opened is one that doesn't match browser locale, nuxt-i18n will redirect to it (`en` in this case).

Manual repro for this fixture is to start up a local server, open incognito/private window and go directly to http://127.0.0.1:8080/af/.

Probably for your tests, it would make sense to disable `detectBrowserLanguage` option.

(And while I find the behavior a bit weird too, it's not that obvious how to improve that so that it works in all possible cases (differing browser languages vs. URL that we navigate to initially vs. different prefix strategies). So even if one could argue it's not ideal, it's more a missing feature than a bug.)

**Comment by pimlie** [comment]
Can confirm that `detectBrowserLanguage` fixes the test. Strangly I cannot reproduce this error when I load the static generated files in my browser, then I just get the /af/ page.

But I dont think that detectBrowserLanguage should do anything if I browse to a specific locale page, that should only work when its unknown which locale the user needs. If I specifically browser to /af/ then you already know which locale I want to see

**Comment by rchl** [comment]
For `nuxt-i18n`, locale is unknown until the `i18n_redirected` cookie is set. That's the simple logic right now. Anything more complex needs should be treated as a feature request IMO as it needs to be properly thought out, implemented and tested.

For example, since with `prefix_and_default` strategy all locales have prefix, how to decide if navigating to /en/ should redirect? There are a couple of cases to consider:
 1) browser locale is `af`, default locale is `en`
 2) browser locale is `en`, default locale is `af`
 3) browser locale is `xx`, default locale is `yy`

I think it's not that obvious how to handle all the cases.

**Comment by pimlie** [comment]
But you know the locale from the route, why would anyone care about browser settings or redirecting if I already tell you I want to see the af page? Especially for the `prefix_and_default` setting, there you should only care about automatically setting the locale for the `default` and not for any `prefixed` routes.

Feature or not, something in 6.2 introduces this breaking change ;)

**Comment by rchl** [comment]
#378 is the change that introduced this behavior change but I would argue it's still a bug fix as it has aligned browser language detection behavior for `universal` and `generated` cases. And while that redirection logic is a bit stupid, it's now consistent at least.

It might be a good enough logic to only trigger redirection when the initial request is to non-default locale route but I can't tell for sure now without testing more. And it would be a breaking change for sure.

Previously detection code didn't run at all for generated page as it was triggered from middleware which [doesn't run for initial request in generated page](https://github.com/nuxt/rfcs/issues/28#issuecomment-527939500).

**Comment by rchl** [comment]
Created #455
