### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by webcoderkz** [nuxt-community/nuxt-i18n#494]
Do you plan to make it compatible with TypeScript?

**Comment by rchl** [comment]
What do you mean exactly by that?

In a typescript project, you can still run plain javascript code. And since this project includes type definitions that cover configuration, Vue and Nuxt context, it should be perfectly usable in a typescript project.

That said, it shouldn't be too hard to rewrite it in Typescript but it's not a priority right now.

**Comment by webcoderkz** [comment]
I see, it has type definitions, ok.
