### ISSUE TITLE
nuxtI18n paths

### ISSUE THREAD

**Issue by mojtaba06** [nuxt-community/nuxt-i18n#512]
### What problem does this feature solve?

We cannot name the paths in the translation files. [ $t('contact.title') ]
It would be nice if we could use the $t in the paths, Instead of typing the name of the path on each page.

#### Now we should do this:
<script>
    export default {
        name: "contact",
        nuxtI18n: {
            paths: {
                en: '/contact-us',
                fa: '/تماس-با-ما',
            }
        }
    }
</script>

#### I suggest that change the code to we can use this code:
<script>
    export default {
        name: "contact",
        nuxtI18n: {
            path: {
                $t('contact.title')
            }
        }
    }
</script>

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c333">#c333</a>)</em></sub></div>

**Comment by rchl** [comment]
At the point of parsing those options, we don't have Vue initialized and so also no access to `$t`. We don't even load translations at this point. It would feel very hacky to try to support that in this context. I don't think I will be working on that as I don't see a clean way of implementing it...

The only thing is I can give is a suggestion to switch to using https://nuxt-community.github.io/nuxt-i18n/routing.html#custom-paths. When configuring paths from `nuxt.config`, you can load your translation files manually and get the needed value so that you can generate your options. It's a bit of work but should be doable.

**Comment by mojtaba06** [comment]
@rchl Thanks for your accountability. As you mentioned I will use the current method to do this. We can close this issue. Good luck.

**Comment by linaslev** [comment]
I am searching for a solution to the same problem. I managed to generate a nice formatted `paths` variable and it generates translated routes totally fine (I see that in the `router.js` file).
This is the approach:
```
// pages/mypage.vue

nuxtI18n: {
     paths: require('../../../../plugins/generateLocaleRoutes.js')('/my-route-name')
},
```

What this required function does, is reading generated translation files and finding the translation for `/my-route-name` for all locales and returning a nicely formatted object like asked here https://nuxt-community.github.io/nuxt-i18n/routing.html#custom-paths Works like a charm and does its job!

**However**, the problem is, that when the page is generated, the required function is being passed to the template, so when you try to open the page it has an error `Cannot find module '../../../../plugins/generateLocaleRoutes.js'`

Do you know a way to solve this?

I was thinking about removing `nuxtI18n` config variable during page generation, but I can't find a way of doing that.

**Comment by rchl** [comment]
@linaslev I believe that options that are only required when building nuxt could just not be passed to client code which should fix it.
