### ISSUE TITLE
failure for android mobile phone

### ISSUE THREAD

**Issue by ZhongkaiChen** [nuxt-community/nuxt-i18n#530]
### Version

[v6.3.0](https://github.com/nuxt-i18n/releases/tag/v6.3.0)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-vovsx](https://codesandbox.io/s/codesandbox-nuxt-vovsx)

### Steps to reproduce

Just follow the basic introduction.

### What is expected ?

Working on an Android mobile phone. 

### What is actually happening?

For android phone, when I open the webpage https://vovsx.sse.codesandbox.io/
I cannot switch languages.
 

### Additional comments?

This issue is quite important since there are so many android phones out there. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c343">#c343</a>)</em></sub></div>

**Comment by ZhongkaiChen** [comment]
Hi,
 I have tried to work on an android phone. 
I also used "switchLocalePath('en')" with no luck. 
The URL changed from "/about" to "/cn/about" for instance.
Nevertheless, the language didn't change. 
If I reload "/cn/about", the language changed to Chinese. 
If I stay in "/cn/about", and click nuxt-link to another page, 
the url will be something like "/project" with no "/cn".

**Comment by ZhongkaiChen** [comment]
I am not sure where the problem came from, I used different android phones and all of them have similar issues.

**Comment by rchl** [comment]
It works for me. There must be something wrong going on on your end. Maybe try debugging your phone through USB  and check for any errors in the console.

**Comment by ZhongkaiChen** [comment]
The problem is partially solved by this.$root.$i18n.locale = lang and then this.$router.push(this.switchLocalePath(lang));
<nuxt-link class="navbar-item" :to="switchLocalePath('en')">
Doesn't work properly in my case.

**Comment by ZhongkaiChen** [comment]
nuxt-link doesn't work properly with ":to="switchLocalePath('en')"
For me, it's enough, but I hope someone can look into the problem and fix it.

**Comment by rchl** [comment]
> The URL changed from "/about" to "/cn/about" for instance.
> the url will be something like "/project" with no "/cn".

Your reproduction doesn't even include `cn` locale. Nor a route called `project`. Sorry, I can't help you there. It could be that your browser is doing something that it shouldn't or you are getting your data modified in transit (since you seem to be Chinese, I wouldn't rule that out given what's happening in China).

I would suggest you try testing in:
 - "private" mode
 - different browser
 - clear out browser cache
 - with VPN

**Comment by gotexis** [comment]
i seem to be having the same issue

**Comment by rchl** [comment]
@gotexis Then provide reproduction. I can't do anything about it otherwise.

**Comment by gotexis** [comment]
@rchl Thanks for your prompt reply!

After a bit of further investigation, my scenario is different. My android phone (chrome) works, but iPhone doesn't (both safari and chrome).

https://goldten.com.au (the lang switcher is on the top right)

weird....

**Comment by rchl** [comment]
I don't have iPhone but it works both on my Desktop Safari and iPhone simulator.
So more info is needed (versions that reproduce at least).

**Comment by gotexis** [comment]
@rchl Thanks for your debugging, i have just updated my site so that it works for iphone now.

Unfortunately what I had to do is to force a refresh on the component by giving it a `key=$route.path`

This is a sledgehammer method, I know its inefficient, but it works for me at this time. I will be closely monitoring if anything like this happen in the future

Thanks
