### ISSUE TITLE
no param support in getRouteBaseName

### ISSUE THREAD

**Issue by bayun2** [nuxt-community/nuxt-i18n#539]
### Version

[v6.3.1](https://github.com/nuxt-i18n/releases/tag/v6.3.1)

### Reproduction link

[https://jsbin.com/?html,js,output](https://jsbin.com/?html,js,output)

### Steps to reproduce

app.getRouteBaseName(route.to) 

### What is expected ?

give the name where route will going

### What is actually happening?

give the name of current route

### Additional comments?

My old project use getRouteBaseName to get route's name ,not only get current route name

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c349">#c349</a>)</em></sub></div>

**Comment by rchl** [comment]
Can you explain your use case in details? There might be another way to achieve what you want to achieve.

**Comment by bayun2** [comment]
For example, I have two routes '/en/page1' 、'/en/page2'.   When i in page1, i want to get page2's routeName. In old version, i get it by use app.getRouteBaseName(route[page2]), but In latest version, getRouteBaseName abort pass param, only return current route's routeName. In my case, i get page1's name not page2

**Comment by rchl** [comment]
- `getRouteBaseName` has never accepted a parameter. At least not since I started working on this module which is a year or so.
 - Your comment still doesn't explain why you need that. If you would explain your use case, maybe I could suggest different way to do the same.
 - If I would go implement such create, what would be the argument to pass to that function? You can only refer route by it's name (as far as I can tell), so if you would have to pass route name then it means that you already know the base name.

**Comment by bayun2** [comment]
- https://nuxt-community.github.io/nuxt-i18n/api/#getroutebasename  in this doc, it's allow to accepted a parameter(route (type: string | Location, default: current route)), then return string

- I use this method to formate route to string By old version。Of coures, i can write a method to get that

**Comment by rchl** [comment]
Crap, you're right. I will fix that. Sorry for talking nonsense. :)
