### ISSUE TITLE
Visiting a locale version of the website redirects to home page (default locale).

### ISSUE THREAD

**Issue by wahidrahim** [nuxt-community/nuxt-i18n#542]
### Version

[v6.4.0](https://github.com/nuxt-i18n/releases/tag/v6.4.0)

### Reproduction link

[https://upbeat-mccarthy-caa106.netlify.com/fr](https://upbeat-mccarthy-caa106.netlify.com/fr)

### Steps to reproduce

1. Open a new Incognito browser:

2. Visit https://upbeat-mccarthy-caa106.netlify.com/fr 

Notice it redirects to: https://upbeat-mccarthy-caa106.netlify.com/

Try visiting https://upbeat-mccarthy-caa106.netlify.com/fr again, but this time it will show the French version as expected.

### What is expected ?

It should go directly to the French version: https://upbeat-mccarthy-caa106.netlify.com/fr

### What is actually happening?

It redirects to English (default) locale: https://upbeat-mccarthy-caa106.netlify.com/

### Additional comments?

How to make it so it goes to the selected locale version as expected?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c351">#c351</a>)</em></sub></div>

**Comment by rchl** [comment]
The first time it redirects based on the prefered language set in the browser because locale cookie is not set yet.

The second time it doesn't redirect anymore because the cookie is there and `alwaysRedirect` option is not set.

So I think the behaviour is correct although it might seem un-optimal that going straight to specific locale still redirects. Also see #455 which is probably what you would also expect here.

**Comment by wahidrahim** [comment]
@rchl Thanks for clarifying the issue! I see this is literally a feature not a bug. After reading the documentation about this, I see I can modify this behaviour with `detectBrowserLanguage` option. I know what to do from here. Thank you!

Closing, as this is not a bug.
