### ISSUE TITLE
Dynamic translation

### ISSUE THREAD

**Issue by sp0ken** [nuxt-community/nuxt-i18n#559]
### What problem does this feature solve?

This feature will allow translation to be dynamically loaded based on a route parameter.

e.g. a route _parameter.vue could load a 'my-parameter.json' translation file

### What does the proposed changes look like?

```
i18n(context) {
      messages: {
        es: require(`~/locales/es/${context.params.parameter}.json`),
        fr: require(`~/locales/fr/${context.params.parameter}.json`),
        it: require(`~/locales/it/${context.params.parameter}.json`)
      }
    },
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c368">#c368</a>)</em></sub></div>

**Comment by rchl** [comment]
In what kind of project do you think it would be beneficial to have this feature?

 - I'm thinking that in small projects it's fine to load strings globally since the size of string is not a problem.
 - In big projects, if there is really a lot of route-specific strings, it could improve bundle size but personally I think it would be a nightmare to work with such setup. I mean, you probably have some strings that are used on all pages so those would have to be merged (or duplicated but that doesn't sound good).

What kind of project size (strings wise) are we talking about here, where this extra complexity would be justified?

**Comment by sp0ken** [comment]
Our current page setup is the following:

- We statically generate our page
- We have a main product page (mattress) where the bulk of the text is in a translation file
- We developped "satellite" pages based on it (mattress-king, mattress-queen, etc.) and they are stand-alone pages (i.e. mattress-king.vue). The translation file is also stand-alone (mattress-king.json)
- We'd like to switch to a dynamic route to reduce code duplication but are limited by the translation file. Hence the dynamic solution suggested.

**Comment by rchl** [comment]
Actually you might be able to do that already. Check https://nuxt-community.github.io/nuxt-i18n/vue-i18n-loader.html and `vue-i18n-loader` documentation, https://github.com/kazupon/vue-i18n-loader#source-importing specifically.

In that solution, you can't have dynamic variables for defining the translation file name, but maybe that would be enough.

**Comment by sp0ken** [comment]
Thanks for the link @rchl.

Unfortunately it seems that dynamic i18n blocks are still in proposal in vue-i18n.

**Comment by rchl** [comment]
`vue-i18n-loader` is a separate project and it's implemented already so not sure what you mean.

**Comment by sp0ken** [comment]
My bad, I check the vue-i18n-loader documentation to see if it could solve the issue but above but unfortunately I didn't see anything to that effect.

There is a proposal to enable dynamic source importing though.
