### ISSUE TITLE
alwaysRedirect not working after update to 6.6.0

### ISSUE THREAD

**Issue by miteyema** [nuxt-community/nuxt-i18n#620]
### Version

[6.6.0](https://github.com/nuxt-i18n/releases/tag/6.6.0)

### Reproduction link

[https://github.com/miteyema/nuxt-i18n-demo](https://github.com/miteyema/nuxt-i18n-demo)

### Steps to reproduce

Before version 6.6.0, I used the following options (as presented in the documentation on (https://nuxt-community.github.io/nuxt-i18n/browser-language-detection.html):
```
 detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirect',
      alwaysRedirect: true
    }
```

### What is expected ?

- rewrite URL to new language
- page content is translated to selected language
- navigation through site is with newly selected language

### What is actually happening?

- rewrite URL to new language
- page content is NOT translated to selected language
- when navigating to another link within the site, the old language is still being used in the URL

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c405">#c405</a>)</em></sub></div>

**Comment by rchl** [comment]
Since you have `alwaysRedirect` enabled, you need to update the locale cookie so that it doesn't redirect to stored locale always. The part where URL changes but not locale is a bug but to change locale you need to update the cookie. See https://nuxt-community.github.io/nuxt-i18n/lang-switcher.html#lang-switcher which tells how to handle that.

(But I agree that something could be improved to make this more clear. Either documentation or maybe extra warning).

**Comment by miteyema** [comment]
@rchl Thanks, I have updated my demo repo and it now works when I use `setLocale(locale)`

**Comment by rchl** [comment]
And I've updated documentation to make this more clear.
