### ISSUE TITLE
Fetching data in layouts

### ISSUE THREAD

**Issue by Jassmin586** [nuxt-community/nuxt-i18n#681]
### Version
nuxt-i18n: 6.9.3
nuxt: 2.12.2

### Reproduction Link
https://codesandbox.io/s/dawn-sunset-g6myt?file=/layouts/default.vue

### Steps to reproduce
1. Add request to fetch method in layout file
2. Switch between languages

### What is Expected?

After changing language fetch method should be run like in middleware.

### What is actually happening?

After changing language the data is still the same because fetch didn't reload.

**Comment by rchl** [comment]
I think that this behavior is not related to `nuxt-i18n` and it's not responsibility of this module to fall `fetch()`.

All that happens in the testcase that is relevant, is we are navigating to a different route using `n-link`. You should be able to reproduce that without `nuxt-i18n` just navigating to a different route instead of using `switchLocalePath`.

And the reason that `fetch()` is not called on navigating, I believe, is because `fetch()` is in the layout, and navigating to a different route doesn't re-create layout. But I haven't played with `fetch()` so I'm not sure how it behaves exactly.

**Comment by rchl** [comment]
Here is an example with no `nuxt-i18n`: https://codesandbox.io/s/fetch-from-layout-on-navigation-yt138
Behaves the same.

**Comment by lazaroofarrill** [comment]
I know this is not an i18n problem but, what would be the correct approach to handle this specific case?
