### ISSUE TITLE
multiple domains analytics

### ISSUE THREAD

**Issue by gianniskarmas** [nuxt-community/nuxt-i18n#713]
While using multiple domains how should google analytics module get set up?
Any way to connect the domains from i18n to GA or env vars is the only way to go?
Trying to set up everything within nuxt and not going through env vars on each of the 12 domains.

**Comment by rchl** [comment]
Does each of those domains need to use a different GA ID? If not, what needs to differ per domain?

In any case, something would have to be done in the GA module itself (I'm assuming you are talking about https://github.com/nuxt-community/analytics-module) as currently it takes options and resolves them at build time and that won't help you if you want to dynamically change GA settings based on domain.

I think there is nothing that `nuxt-i18n` needs to provide to facilitate that. Rather than GA module itself. Therefore I'm gonna close this. Let me know if you have some ideas on how `nuxt-i18n` could help here.
