### ISSUE TITLE
Command for extracting / collecting messages

### ISSUE THREAD

**Issue by vonlu3** [nuxt-community/nuxt-i18n#739]
### Problem
In most projects the translatable strings nor the translations are not ready at the beginning. As you progress with the project you define the translatable strings but forgetting or just don't want to add the strings to the translation file each time. After finishing the base layout or a feature you have to go trough the files and searching for all translatable strings manually. 

### Solution
It would be really nice to have a command for extracting / collecting all translatable strings from the *.vue files and write it to the translation files in each configured language. Of course the script should not overwrite existing translations nor delete unused ones. 

Another use case is to extract all messages in the CI process and send it to a translation API. In the translation API the customer can translate the strings in a fancy interface. Then we can load the translation from the API while generating the static pages or serving requests in SSR mode.

### Alternatives
Just be more disciplined and update the translation files by hand 😄 .

### Additional context
Repo for same feature in vue-i18n:
https://github.com/pixari/vue-i18n-extract

**Comment by rchl** [comment]
From the perspective of someone maintaining such functionality, I'd be very hesitant to include it. It's because it's inherently broken. It requires a lot of self-discipline to get accurate results. It won't properly catch dynamic uses of a key (when they come from API, for example, or are just JS variables resolved at runtime). It will likely break in many other cases too.

It's the same with projects that try to extract *actually used* CSS from pages. Those things also break all the time and are not reliable.

From the maintainer's perspective it's a nightmare because people expect those things to work perfectly and will report bugs or questions if something isn't quite right.

I haven't tried https://github.com/pixari/vue-i18n-extract but maybe it's an option to just run that thing on the side of Nuxt project (`nuxt-i18n` is, after all, using `vue-i18n` under the hood)? Why would it be necessary for `nuxt-i18n` to integrate something like that and how would you see it being integrated?

**Comment by vonlu3** [comment]
Thanks for your very fast answer and your time. I definitely don't consider this feature as  necessary for nuxt-i18n but a nice to have.

> From the maintainer's perspective, it's a nightmare because people expect those things to work perfectly and will report bugs or questions if something isn't quite right.

I see your point and if I think about it, I would rather avoid to support this kind of feature too.
I will implement it myself and if I make the repo public then without maintaining or support.

Your probably right about vue-i18n-extract but this is one of the only solutions which tries to takle the issue.
